image: registry.gitlab.com/serebit/wraith-master:latest

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  GRADLE_USER_HOME: $CI_PROJECT_DIR/.gradle
  KONAN_DATA_DIR: $CI_PROJECT_DIR/.konan

before_script:
  - rm -f $GRADLE_USER_HOME/caches/modules-2/modules-2.lock
  - rm -f $GRADLE_USER_HOME/caches/build-cache-1/build-cache-1.lock
  - mkdir -p $KONAN_DATA_DIR/cache
  - ln -s /var/lib/konan/deps/* $KONAN_DATA_DIR/cache/

cache:
  key: one-key-to-rule-them-all
  paths:
    - $GRADLE_USER_HOME/wrapper/dists/
    - $GRADLE_USER_HOME/caches/modules-2/
    - $GRADLE_USER_HOME/caches/build-cache-1/
    - $KONAN_DATA_DIR/kotlin-native-*

build:
  stage: build
  script: ./gradlew build
  artifacts:
    paths:
      - "**/build/classes"
      - "**/build/libs"
  except:
    changes:
      - README.md
      - LICENSE.md
      - CHANGELOG.md
      - FUNDING.yml

release-tar:
  stage: deploy
  dependencies:
    - build
  when: manual
  only:
    refs:
      - master
  script: ./gradlew distTar
  artifacts:
    paths:
      - "build/dist/*.tar.*"

release-deb:
  stage: deploy
  dependencies:
    - build
  when: manual
  only:
    refs:
      - master
  script:
    - ./gradlew install -Ppackageroot=$CI_PROJECT_DIR/build/debian/wraith-master
    - install -D resources/debian-control.txt build/debian/wraith-master/DEBIAN/control
    - cd build/debian
    - dpkg-deb -b wraith-master
  artifacts:
    paths:
      - "build/debian/wraith-master.deb"
